steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cosmic-kiln-410709/testing', './dockerfiles/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cosmic-kiln-410709/testing']