steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cosmic-kiln-410709/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cosmic-kiln-410709/testing']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'gcp-test-app'
  - '--image'
  - 'gcr.io/cosmic-kiln-410709/testing:latest'
  - '--region'
  - 'europe-west1'
images:
  - 'gcr.io/cosmic-kiln-410709/testing:latest'